# -*- coding: utf-8 -*-
"""StatisticalModeling-0326.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8P1Qr5z48KP58ZvcfzKC2o1eRZn6xTj

데이터셋 불러오기
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import skew

# 데이터 로드
boston = fetch_openml(name="boston", version=1, as_frame=True)
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df['y'] = boston.target

# 데이터 요약
print(df.describe())
print(df.dtypes)

"""독립변수 feature 탐색"""

## 변수별 왜도 -> 분포 확인
# categorical -> float 변환
df['CHAS'] = df['CHAS'].astype(float)
df['RAD'] = df['RAD'].astype(float)
# 왜도 계싼
skewness = df.apply(skew).sort_values(ascending=False)
print("\n (Skewness):\n", skewness)
# 분포 시각화 + 왜도값 출력
for col in df.columns[:-1]: # y 제외
skew_val = skew(df[col]) # 해당 변수의 왜도
plt.figure(figsize=(10, 4))
sns.histplot(df[col], kde=True, bins=30, color='skyblue')
plt.title(f'Distribution: {col} (Skewness: {skew_val:.2f})')
plt.xlabel(col)
plt.ylabel('Count')
plt.grid(True)
plt.tight_layout()
plt.show()

"""변수 변환"""

df_transformed = df.copy()
# 로그 변환 적용
log_vars = ['CRIM', 'NOX', 'DIS', 'LSTAT']
for col in log_vars:
  df_transformed[col + '_log'] = np.log1p(df[col])

# 제곱근 변환 적용
sqrt_vars = ['AGE', 'TAX', 'PTRATIO']
for col in sqrt_vars:
  df_transformed[col + '_sqrt'] = np.sqrt(df[col] - df[col].min() + 1)keep_vars = ['RM', 'ZN', 'INDUS', 'CHAS', 'RAD', 'B']

selected_features = [v + '_log' for v in log_vars] + [v + '_sqrt' for v in sqrt_vars] + keep_vars
X = df_transformed[selected_features]

# 스케일링
# https://scikitlearn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.htmlscaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y = df_transformed['y']

